import { useEffect, useRef, useState } from 'react';
import {
  AlertTriangle,
  CalendarClock,
  CheckCircle2,
  CircleDot,
  ClipboardCheck,
  Clock3,
  FileText,
  Lightbulb,
  Loader2,
  Play,
  Sparkles,
  TrendingUp
} from 'lucide-react';
import type { PlanAdjustmentProposal, ReviewResult, TodayGuideState } from '../../../shared/types';
import type { ViewKey } from '../types/navigation';
import type { LocalSettlement } from '../types/settlement';

export function ReviewPage({
  review,
  todayGuide,
  latestSettlement,
  pendingAdjustment,
  autoGenerate,
  onAutoGenerated,
  onGenerate,
  hasApiKey,
  onDecideAdjustment,
  onGoTo
}: {
  review: ReviewResult | null;
  todayGuide: TodayGuideState | null;
  latestSettlement: LocalSettlement | null;
  pendingAdjustment: PlanAdjustmentProposal | null;
  autoGenerate: boolean;
  onAutoGenerated: () => void;
  onGenerate: () => Promise<void>;
  hasApiKey: boolean;
  onDecideAdjustment: (proposalId: string, status: 'accepted' | 'rejected') => Promise<void>;
  onGoTo: (view: ViewKey) => void;
}): JSX.Element {
  const [generating, setGenerating] = useState(false);
  const autoTriggeredRef = useRef(false);

  // Reset auto-trigger guard when autoGenerate flag changes
  useEffect(() => {
    if (!autoGenerate) {
      autoTriggeredRef.current = false;
    }
  }, [autoGenerate]);

  // Auto-generate review when navigating from settlement
  useEffect(() => {
    if (autoGenerate && !review && hasApiKey && !autoTriggeredRef.current) {
      autoTriggeredRef.current = true;
      onAutoGenerated();
      setGenerating(true);
      void onGenerate().finally(() => setGenerating(false));
    }
  }, [autoGenerate, review, hasApiKey]);

  const allActions = review?.nextActions ?? [];
  const totalCount = allActions.length;
  const settlementMinutes = latestSettlement
    ? Math.max(1, Math.round(latestSettlement.elapsedSeconds / 60))
    : 0;
  const completionScore = review?.completionScore ?? (latestSettlement ? 65 : 0);
  const focusScore = review?.focusScore ?? (latestSettlement ? 75 : 0);
  const stageProgress = review ? 25 : latestSettlement ? 20 : 0;

  const plannedTasksTotal = todayGuide?.guide?.tasks.length ?? 0;
  const tasksTotal = Math.max(plannedTasksTotal, latestSettlement ? 1 : 0);
  const tasksDone = completionScore >= 80 ? tasksTotal : completionScore > 0 ? Math.max(0, tasksTotal - 1) : 0;
  const last7Days = [
    { label: '05/10', value: 45 },
    { label: '05/11', value: 72 },
    { label: '05/12', value: 54 },
    { label: '05/13', value: 68 },
    { label: '05/14', value: 61 },
    { label: '05/15', value: 48 },
    { label: '05/16', value: settlementMinutes || 0 }
  ];
  const maxBar = Math.max(...last7Days.map((d) => d.value), 78);
  const blockerItems = focusScore < 70
    ? ['专注稳定性仍需提升']
    : ['暂未记录明显卡点'];
  const suggestionItems = allActions.length
    ? allActions.slice(0, 3)
    : pendingAdjustment?.reason
      ? [pendingAdjustment.reason]
      : ['保持当前节奏，继续完成剩余任务'];

  return (
    <section className="review-layout">
      <div className="review-main">
        <header className="page-title-block">
          <h1>复盘</h1>
          <p>回顾今天的完成情况，形成可持续的学习节奏</p>
        </header>

        <section className="review-stats-row">
          <div className="review-stat-card">
            <CheckCircle2 size={28} />
            <div>
              <span>今日完成</span>
              <strong>{tasksDone}/{tasksTotal} 任务</strong>
            </div>
          </div>
          <div className="review-stat-card">
            <Clock3 size={28} />
            <div>
              <span>学习时长</span>
              <strong>{settlementMinutes > 0 ? `${settlementMinutes} 分钟` : '-'}</strong>
            </div>
          </div>
          <div className="review-stat-card">
            <TrendingUp size={28} />
            <div>
              <span>完成率</span>
              <strong>{completionScore}%</strong>
            </div>
          </div>
        </section>

        <section className="surface review-summary-card">
          <div className="review-summary-header">
            <span className="summary-icon"><FileText size={22} /></span>
            <div>
              <strong>本次学习总结</strong>
              <p>{review ? review.summary : latestSettlement?.notes || '完成学习后生成总结。'}</p>
            </div>
          </div>
          <div className="review-tag-row">
            <span><CircleDot size={12} />已完成提交记录</span>
            <span><CircleDot size={12} />掌握基础分支操作</span>
            <span className="warning"><CircleDot size={12} />需继续练习冲突处理</span>
          </div>
        </section>

        <section className="surface review-timeline-card">
          <h3>学习记录</h3>
          {!latestSettlement && !review && (
            <p className="muted">暂无学习记录，完成一次学习后会在这里汇总。</p>
          )}
          <div className="review-timeline">
            {latestSettlement && (
              <>
                <div className="timeline-item">
                  <span className="timeline-dot" />
                  <span className="timeline-time">{latestSettlement.session.startedAt.slice(11, 16)}</span>
                  <span className="timeline-text">开始学习</span>
                </div>
                <div className="timeline-item">
                  <span className="timeline-dot" />
                  <span className="timeline-time">-</span>
                  <span className="timeline-text">完成本次学习 · {settlementMinutes} 分钟</span>
                </div>
              </>
            )}
            {review && (
              <div className="timeline-item">
                <span className="timeline-dot" />
                <span className="timeline-time">-</span>
                <span className="timeline-text">生成复盘 · {completionScore}% 完成率</span>
              </div>
            )}
          </div>
        </section>

        {pendingAdjustment?.status === 'pending' && (
          <section className="surface review-adjustment-card">
            <h3>调整建议</h3>
            <p className="muted">AI 建议只有经你确认后才会生效。</p>
            <div className="review-decision-actions">
              <button
                className="primary-action"
                type="button"
                onClick={() => void onDecideAdjustment(pendingAdjustment.id, 'accepted')}
              >
                <CheckCircle2 size={16} />
                采纳建议
              </button>
              <button
                className="secondary-action"
                type="button"
                onClick={() => void onDecideAdjustment(pendingAdjustment.id, 'rejected')}
              >
                <ClipboardCheck size={16} />
                保持原计划
              </button>
            </div>
          </section>
        )}

        {!review && latestSettlement && hasApiKey && !generating && (
          <button className="primary-action review-generate-action" type="button" onClick={() => void onGenerate()}>
            <Sparkles size={16} />
            生成 AI 复盘
          </button>
        )}
        {generating && (
          <div className="micro-hint">
            <Loader2 className="spin" size={16} />
            正在生成复盘…
          </div>
        )}

        <div className="review-footer-actions">
          <button className="primary-action" type="button" onClick={() => onGoTo('today')}>
            <Play size={16} />
            开始下一次学习
          </button>
          <button className="secondary-action" type="button" onClick={() => onGoTo('review')}>
            <CalendarClock size={16} />
            查看全部历史
          </button>
        </div>
      </div>

      <aside className="review-side">
        <section className="context-card chart-card">
          <div className="chart-header">
            <h3>最近 7 天</h3>
            <span className="muted">单位：分钟</span>
          </div>
          <div className="mini-bar-chart">
            {last7Days.map((day) => (
              <div className="bar-column" key={day.label}>
                <div className="bar-track">
                  <div className="bar-fill" style={{ height: maxBar ? `${(day.value / maxBar) * 100}%` : '0%' }} />
                </div>
                <span>{day.label}</span>
              </div>
            ))}
          </div>
        </section>

        <section className="context-card issue-card">
          <h3>问题与改进</h3>
          <div className="issue-block">
            <strong><AlertTriangle size={16} /> 本次卡点</strong>
            <ul>
              {blockerItems.map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </div>
          <div className="issue-block">
            <strong><Lightbulb size={16} /> 下一步建议</strong>
            <ul>
              {suggestionItems.map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </div>
        </section>

        <section className="context-card review-note-card">
          <h3>复盘笔记</h3>
          <textarea placeholder="记录对今日学习的感受、收获与需要改进的事项…" maxLength={300} />
          <div>
            <span>0 / 300</span>
            <button className="secondary-action" type="button">保存笔记</button>
          </div>
        </section>
      </aside>
    </section>
  );
}


